### ISSUE TITLE
[Option request] Use system emojis

### ISSUE THREAD

**Issue by dmlls** [GaZaTu/x11-emoji-picker#17]
First of all, thanks for this great color picker! 🙂

I understand that bundling an emoji pack (i.e.., Twemoji) together with the color picker makes sense from the point of view of ensuring that emojis will be correctly displayed inside the color picker. However, since I don't use Twemoji in my system, there is inconsistency between the emojis displayed in the color picker, and how they appear on my system after inserting them.

Therefore, it might be useful to have an option that allows using the system emojis (disabled by default). Is this doable/does it make sense to you?

**Comment by GaZaTu** [comment]
ye sure makes sense, gonna look into it later this afternoon 😊

**Comment by GaZaTu** [comment]
@dmlls @zneix check out #18 and tell me what you think / if it works for your installed emoji font

**Comment by dmlls** [comment]
Wow, thanks for the quick response!

So it does work 🥳 Only issue is that missing emojis that expand to several emojis mess with the alignment:

![Screenshot_20220126_230549](https://user-images.githubusercontent.com/22967053/151255002-77d452ed-9b84-40b0-91e9-7a91e430373f.png)

I know this is not your fault though ;) I wonder if it would be possible to not display unsupported emojis? That way the user wouldn't have to manually configure the Unicode version.

For unsupported, multiple-codepoint emojis (i.e., those which will expand to several emojis) a simple heuristic would be checking if they occupy more space than a single emoji, and in that case, consider them unsupported and not show them.

**Comment by zneix** [comment]
> Wow, thanks for the quick response!
> 
> So it does work partying_face Only issue is that missing emojis that expand to several emojis mess with the alignment:

I'm pretty sure this is the cause of some combined emojis being incorrectly renderred, I experience same/similar issue on my end: 
![donkzatu](https://cdn.zneix.eu/wf4DeU7.png)

**Comment by GaZaTu** [comment]
@dmlls you're right i forgot to mention this issue. I guess i could look into some kind of heuristic, but what i actually had planned was to set `maxEmojiVersion` in the emoji picker to the version supported by your font (12 for example). See the [4th paragraph in the updated readme](https://github.com/GaZaTu/x11-emoji-picker/blob/6a9f4afe0ae038cacfed06eb6afccc0704de4062/README.md#notes).

@zneix thats not actually the same issue, because here the emoji font simply doesn't support the emoji itself yet (e.g. it doesn't have an image for it) and so it shows them separately.

**Comment by dmlls** [comment]
Maybe you could set a fixed size an emoji can take, and if it takes more (i.e., the emoji has expanded into several emojis), simply scale it down? This is similar to how KDE's emoji picker works (see last row):

![Screenshot_20220127_100827](https://user-images.githubusercontent.com/22967053/151331709-5adc0479-2b3d-40fe-8d76-2f0667e5b4b0.png)

**Comment by GaZaTu** [comment]
ok look this:

![Screenshot_20220127_203855](https://user-images.githubusercontent.com/17497826/151432137-63062585-3725-4147-bea3-46418a704526.png)
