### ISSUE TITLE
Crash on Manjaro

### ISSUE THREAD

**Issue by Mylloon** [GaZaTu/x11-emoji-picker#19]
Hello !

The program does not launch on Manjaro.

(Started from gdb)
```
Starting program: /usr/bin/emoji-picker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[New Thread 0x7ffff34b4640 (LWP 16201)]
[New Thread 0x7ffff139e640 (LWP 16202)]
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
XGetWindowProperty failed!
Thread 1 "emoji-picker" received signal SIGSEGV, Segmentation fault.
0x00007ffff76e5cc3 in xdo_get_pid_window () from /usr/lib/libxdo.so.3
```
My configuration :
OS: Manjaro Linux x86_64
Kernel: 5.15.21-1-MANJARO
DE: GNOME 41.3

**Comment by GaZaTu** [comment]
well it looks like you're running manjaro in a wayland session and while i'd love to support it, it's sadly not really possible to write a tool which inserts text into foreign applications in a wayland session at this time. (i've tried alot of different ways to do this aswell but nothing truly works) 😣

if you're running kde you could also look at the `feature/dbus-daemon` branch and see if that works for you. https://github.com/GaZaTu/x11-emoji-picker/tree/feature/dbus-daemon#wayland-

**Comment by Mylloon** [comment]
Update: On Manjaro there is an option to disable Wayland (Layout -> Settings -> Disable "Wayland Session". Restart the computer and everything is fine 🎉
