### ISSUE TITLE
Default window width causes incorrect wrapping

### ISSUE THREAD

**Issue by eclairevoyant** [GaZaTu/x11-emoji-picker#27]
Was there a specific reason why `w = 374` was chosen for the [main window](../blob/master/src/main.cpp#L96)? It seems to render incorrectly on my machine. I'm not using KDE, just using a WM (qtile) under X. The width seems just slightly small enough to cause incorrect wrapping.

Example of out-of-the-box config (`QWidget` width = 354):
![default_settings](https://user-images.githubusercontent.com/848000/180591334-2bb2bfc9-7112-403a-be65-82e9e818dd63.png)

With the following custom QSS:
```
QWidget {
  width: 358
}
```
![with_qss_change](https://user-images.githubusercontent.com/848000/180591335-52dff73d-459e-4b13-a27a-6307921abd61.png)

I tried all possible combinations of `useSystemEmojiFont` and `useSystemEmojiFontWidthHeuristics` to no benefit, only the QSS seemed to help.

**Comment by GaZaTu** [comment]
mhhh idk it seemed to fit nicely on different systems but i guess you can never be sure. Its weird tho because the emojis should have fixed size.
Would you be fine with a simple config entry like windowWidth to configure it yourself?
I don't really know how to fix it in a proper way 😆

**Comment by eclairevoyant** [comment]
I'm fine with using the qss on my own systems, I'm just thinking of other users who might run into this in the future. I'll probably play around with the qt inspector later to see why it's wrapping on my system, and if the value can be calculated from some system parameters.

**Comment by GaZaTu** [comment]
this is completely fixed now
