### ISSUE TITLE
Ability to list all emoji - preferrably by category

### ISSUE THREAD

**Issue by killermosi** [GaZaTu/x11-emoji-picker#35]
As bad as the current KDE emoji picker is, it has one useful feature that I feel this emoji picker lacks: the ability to list ALL available emojis.

As good as the search feature is, it is not always easy to know what to search for.

Case in point:
1. I was looking for this particular emoji for #34 : 😇
1. I opened the emoji picker and searched for `angel` - some emojis matched, but not this one: 👼👼🏻👼🏼👼🏽👼🏾👼🏿
    * All of them matched due to being named `baby_angel`.
1. I opened the KDE emoji picker and looked through the list, and quickly found it - turns out it is named `smiling_face_with_halo`.

So I think it wold really help to be able to also search visually instead of only textually for a specific emoji.

**Comment by GaZaTu** [comment]
press F2 for a list of all emojis

source: https://github.com/GaZaTu/x11-emoji-picker#keybinds

**Comment by killermosi** [comment]
I tried pressing F2, but if there are more emojis "loaded" in the window than intially visible, it does not seem that I can scroll them - at least not with the mouse wheel. I'll double check tomorrow.

"By category" is something nice to have (as the emoji list is quite large), but far from important.

**Comment by GaZaTu** [comment]
oh right, you can't scroll with mouse atm only with the arrow keys. i guess being able to scroll with mouse is something you want?

**Comment by killermosi** [comment]
Well, since the mouse is used for other actions on the emoji picker I expected scrolling with the mouse wheel to work too. It never occured to me to try the keyboard, since emoji picking (sans searching) is a mouse-oriented task.

I feel that it is definitely something that would improve the UX (along with some scrolling progress indicator perhaps), but since scrolling is already possible with the arrow keys, this is not a pressing issue.

**Comment by GaZaTu** [comment]
its kinda scuffed as it just replicates the arrow key behaviour but atleast you can kinda scroll with mouse now.
regarding list by category: kinda big feature that i'm too lazy to implement as of right now. 🫣

**Comment by killermosi** [comment]
Thanks for the scroll, I'll give it a test drive.

Don't worry about categories for now 👍
