### ISSUE TITLE
openAtMouseLocation is not respected on xfce4/xfwm4

### ISSUE THREAD

**Issue by schrmh** [GaZaTu/x11-emoji-picker#45]
I have two monitors connected and it looks like the emoji-picker window always opens in the middle of the screen with the window I want to input emojis to instead of the actual mouse position.

**Comment by schrmh** [comment]
As already commented in #46: this doesn't play well with QT_SCALE_FACTOR.
Also it would be nice to have some option to prevent that the picker is outside the screen: 
![image](https://user-images.githubusercontent.com/32062480/220087778-9fdc9f58-1d8d-455d-b211-a7b68294ca09.png)

**Comment by GaZaTu** [comment]
you're right, i'll look into this later

**Comment by GaZaTu** [comment]
> Also it would be nice to have some option to prevent that the picker is partly outside the screen:

This should already be working or is there some specific scenario where it doesn't?

**Comment by schrmh** [comment]
Thanks, with #47 the window is exactly at the position of the mouse pointer, no matter the scale factor.

> This should already be working or is there some specific scenario where it doesn't?

Well, for me it is always partly outside the screen when the distance between mouse and screen edge is smaller than the size of the emoji-picker window.
![image](https://user-images.githubusercontent.com/32062480/220189529-0d584e09-5aa1-417d-bc3c-7f6f94338e72.png)

**Comment by GaZaTu** [comment]
@schrmh you can take a look at #48 it should fix the positioning issue

**Comment by schrmh** [comment]
Thanks, looks like it is working.
