### ISSUE TITLE
Please add category wise emoji selector

### ISSUE THREAD

**Issue by vpsone** [GaZaTu/x11-emoji-picker#50]
If it is possible. Please add category wise emoji selector like this 👇🏽

![image](https://user-images.githubusercontent.com/84894255/224490341-1faa9b84-9000-4d14-a0b5-3a6bbf86b9b5.png)

**Comment by GaZaTu** [comment]
while i agree that this would be a nice feature, i don't know how to design the UI/UX around this without bloating / impacting existing functionality.
