### ISSUE TITLE
Needs Updated to work with new version of icu package

### ISSUE THREAD

**Issue by p134c0d3** [GaZaTu/x11-emoji-picker#53]
Hey! First off, lifesaver program as my wife and I speak in emojis with each other. 
Worked great last night, but this morning, when attempting to run the program, it'll open for a split second, and then close again before the GUI pops up (icon on taskbar shows for a half second).
Attempted to run from terminal and received error 
`emoji-picker: error while loading shared libraries: libicuuc.so.72: cannot open shared object file: No such file or directory`
So I checked my icu package version
`icu 73.2-1`

I'm fairly new to Arch, but does this mean that the emoji-picker is requiring 72, so when the package was upgraded to 73 it broke it?

![image](https://github.com/GaZaTu/x11-emoji-picker/assets/70922864/602b9807-5ccb-49e6-b068-d98c2e0cc2d2)

**Comment by GaZaTu** [comment]
@p134c0d3 I assume you installed from AUR; "-git" packages are not automatically updated by your package manager (I assume you used yay to install x11-emoji-picker-git?) and thus when you upgraded your system it installed a new version of ICU but didn't rebuild x11-emoji-picker.

To fix this you basically need to run `yay --devel`.

There is a package which integrates into pacman and checks for dependency updates of your installed AUR packages but i don't remember what it's called rn. If i remember i'll mention it later.

**Comment by p134c0d3** [comment]
@GaZaTu no I just install the normal `x11-emoji-picker` package. Was trying to stay on the "stable" branch of it.

**Comment by p134c0d3** [comment]
![image](https://github.com/GaZaTu/x11-emoji-picker/assets/70922864/f372ffde-2390-476f-b64b-4bb1ab6d40d8)

**Comment by GaZaTu** [comment]
oh yea but that still seems to build the package on your pc so an update to ICU for example requires you to rebuild x11-emoji-picker as mentioned above.

**Comment by p134c0d3** [comment]
Okay, I removed it, and built the `git` version so that it'd rebuild. Previously when I `yay -Rns x11-emoji-picker` and then `yay -S x11-emoji-picker` it just reinstalled it so had me a little confused. Since it rebuilt it used icu.73 so I'm good now. Thanks for the direction!

**Comment by p134c0d3** [comment]
> oh yea but that still seems to build the package on your pc so an update to ICU for example requires you to rebuild x11-emoji-picker as mentioned above.

Closing with solution above
