### ISSUE TITLE
executable is being extracteed into the wrong location

### ISSUE THREAD

**Issue by y0shir** [GaZaTu/x11-emoji-picker#8]
when installing through .deb executable is extracted into /usr instead of /usr/bin

**Comment by GaZaTu** [comment]
damn thx for creating this issue. 😋
i guess i never actually tried the .deb myself but i fixed it now.

https://github.com/GaZaTu/x11-emoji-picker/releases/download/0.8.0/x11-emoji-picker-0.8.0.x86_64.deb
